AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for Charging Station Service'

Parameters:
  AppName:
    Type: String
    Default: charging-station-service
  Environment:
    Type: String
    Default: prod
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8

Resources:
  # ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref AppName

  # ECS Cluster  
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AppName}-cluster

  # CloudWatch Log Group
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AppName}
      RetentionInDays: 7

Outputs:
  ECRRepositoryURI:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository} 