version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: charging-station-mysql
    environment:
      MYSQL_DATABASE: chargingstation
      MYSQL_USER: chargingstation
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "chargingstation", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 3

  charging-station-service:
    build: .
    container_name: charging-station-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_ENABLED: false
      DB_URL: jdbc:mysql://mysql:3306/chargingstation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      DB_USERNAME: chargingstation
      DB_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/charging-station/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data: 